const NavigationString = {
  Login: "Login",
  Splash: "Splash",
  UserInfo: "UserInfo",
  Home: "Home",
  Otp: "Otp",
  ProductSearchScreen: "ProductSearchScreen",
  Profile: "Profile",
  Categories: "Categories",
  SubCategories: "SubCategories",
  ProductDetail: "ProductDetail",
  Cart: "Cart",
  Brands: "Brands",
  WishListProduct: "WishListProduct",
  Wallet: "Wallet",
  OrderHistory: "OrderHistory",
  OrderHistoryDetail: "OrderHistoryDetail",
  FilterPoroduct: "FilterPoroduct",
  PaymentScreen: "PaymentScreen",
  HelpSupport: "HelpSupport",
  WalletHistory: "WalletHistory",
  BrandDay: "BrandDay",
  Faqs: "Faqs",
  Offers: "Offers",
  PrivacyPolicy: "PrivacyPolicy",
  TermsCondition: "TermsCondition",
  Product: "Product",
  FilterPage: "FilterPage",
};
export default NavigationString;
